dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
  - clang
before_install:
  # install mpir dependencies
  - sudo apt-get -qq update
  - sudo apt-get install -y yasm
install:
  - export CC =which $CC
  # install mpir library
  - wget http://mpir.org/mpir-3.0.0.tar.bz2
  - tar -xvjf mpir-3.0.0.tar.bz2
  - cd mpir-3.0.0/
  - ./configure
  - make -j 2
  - sudo -i make install
  - cd ../
  # install testu01
  - wget http://simul.iro.umontreal.ca/testu01/TestU01.zip
  - unzip TestU01.zip
  - cd TestU01-1.2.3/
  - ./configure
  - make -j 2
  - sudo -i make install
  - cd ../
script:
  - mkdir build
  - cd build
  - cmake .. && make -j 2
